Button on .help, refacto, small bugfix
FrenchDiscord/NostradamusDiscordBot pull request #128
Opened 2021-08-07 17:20 UTC by julienChemin

2021-08-07 17:24 UTC, julienChemin commented on model/command/help.js
> +        this.init(message, Command);
Peu être mettre le contenu de la methode init directement dans le process ?

2021-08-08 15:38 UTC, SpecialFlocon commented on model/command/help.js
> +            callback: async (interaction) => {
Factorize callback method

2021-08-08 15:48 UTC, SpecialFlocon requested changes

2021-08-08 15:48 UTC, SpecialFlocon commented on translations/en.yaml
> +      chooseCategory: "Choose a category"
```suggestion
      pickCategory: "Pick a category"
```

2021-08-08 15:48 UTC, SpecialFlocon commented on translations/fr.yaml
> +      chooseCategory: "Choisissez une catégorie"
```suggestion
      pickCategory: "Choisissez une catégorie"
```

2021-08-08 16:24 UTC, SpecialFlocon approved these changes

2021-08-08 16:24 UTC, merged